# Golang CI pipeline configuration
linters:
  disable-all: true

  # Run golangci-lint linters to see the list of all linters
  # Please keep them sorted alphabetically
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - goconst
    - gofmt
    - goimports
    # - golint # TODO: re-enable, needs breaking change due to wanting IpAddress -> IPAddress
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    # - stylecheck # TODO: re-enable, needs breaking change due to wanting IpAddress -> IPAddress
    - typecheck
    - unconvert
    #    - unparam
    - varcheck
    - whitespace

linters-settings:
  goconst:
    min-len: 5