branches:
  only:
    - master

language: go

go:
  - 1.13.x
  - 1.14.x

env:
  - CGO_ENABLED=0

script: |
  if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    export UPCLOUD_GO_SDK_TEST_NO_CREDENTIALS="yes"
  fi
  travis_wait 20 ./scripts/build.sh
